![Astrofisica Computacional](../../../new_logo.png)

---
# 01. Introduction to `NumPy`

## Dr. rer. nat. Jose Ivan Campos Rozo<sup>1,2</sup>

1. Astronomical Institute of the Czech Academy of Sciences\
   Department of Solar Physics\
   Ondřejov, Czec Republic

2. Observatorio Astronómico Nacional\
   Facultad de Ciencias\
   Universidad Nacional de Colombia

e-mail: jicamposr@unal.edu.co & rozo@asu.cas.cz)

---

<h2 style="white-space:nowrap;margin-bottom: 1px;margin-top: 20px;"><strong>About This Notbook</strong></h2>
        <p style="text-align:justify;margin-top: 5px;margin-bottom: 10px;font-size: 32px;">In this notebook we present a short and fast introduction to the <code>numpy</code> package.</p>
---

In [1]:
import numpy as np
import sys

print(f"Python version:  {sys.version}\n"
      f"NumPy version:   {np.__version__}")


Python version:  3.10.19 | packaged by conda-forge | (main, Oct 22 2025, 22:29:10) [GCC 14.3.0]
NumPy version:   2.2.6


## Arrays in NumPy: `ndarray`

A 1-dimensional array

In [ ]:
a = np.array([1., 2., 3., 4., 5.])
a

In [65]:
type(a)

numpy.ndarray

## Properties of an array

In [66]:
a.size  # Gives the number of elements in the array

5

In [67]:
a.ndim  # Number of dimensions of the array

1

In [68]:
a.shape  # Shape of the array

(5,)

In [69]:
a.dtype  # Type of the elements in the array

dtype('float64')

Multi-dimensional Arrays

In [70]:
b = np.array([[1., 2., 3.],[4., 5., 6.], [7., 8., 9.]])
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [71]:
print(type(b))
print(b.size)
print(b.ndim)
print(b.shape)
print(b.dtype)

<class 'numpy.ndarray'>
9
2
(3, 3)
float64


## Array Methods

In [72]:
a

array([1., 2., 3., 4., 5.])

Minimum, maximum and mean

In [73]:
a.min(), a.max(), a.mean()

(np.float64(1.0), np.float64(5.0), np.float64(3.0))

Sum of elements

In [74]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [75]:
b.sum()

np.float64(45.0)

In [76]:
b.sum(axis=0)

array([12., 15., 18.])

In [77]:
b.sum(axis=1)

array([ 6., 15., 24.])

In [78]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [79]:
b.T # Transpose of b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [80]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [81]:
b = b.T

In [82]:
b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

## Operations with Arrays

In [83]:
a

array([1., 2., 3., 4., 5.])

In [84]:
a + 5.

array([ 6.,  7.,  8.,  9., 10.])

In [85]:
a*np.pi/2.

array([1.57079633, 3.14159265, 4.71238898, 6.28318531, 7.85398163])

$a^e$

In [86]:
a**np.e

array([ 1.        ,  6.58088599, 19.81299075, 43.30806043, 79.43235917])

$e^a$

In [87]:
np.e**a

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

Products of arrays

In [88]:
a

array([1., 2., 3., 4., 5.])

In [89]:
a * a  # Element-wise product

array([ 1.,  4.,  9., 16., 25.])

In [90]:
a @ a  # Matrix Product

np.float64(55.0)

In [91]:
np.dot(a,a) # Equivalent form of the matrix product

np.float64(55.0)

Other operations

In [92]:
a

array([1., 2., 3., 4., 5.])

In [93]:
a < 3

array([ True,  True, False, False, False])

In [94]:
a == 4

array([False, False, False,  True, False])

Other operations

In [95]:
(a > 3) & (a < 5)  # bitwise AND

array([False, False, False,  True, False])

In [96]:
a < np.array([2, 3, 5, 2, 1])

array([ True,  True,  True, False, False])

In [97]:
a

array([1., 2., 3., 4., 5.])

In [98]:
a < 3

array([ True,  True, False, False, False])

In [99]:
np.sum(a < 3) 

np.int64(2)

## Indices and Slicing

In [100]:
a

array([1., 2., 3., 4., 5.])

In [101]:
a[0]  # Remember that indices start at 0

np.float64(1.0)

In [102]:
a[-1]  # Index [-1] refers to the last element

np.float64(5.0)

In [103]:
a[2:6] # Indices [start:end]

array([3., 4., 5.])

In [104]:
a[2:6:2]  # Indices [start:end:step]

array([3., 5.])

In [105]:
a[::-1]  # Reverse an array

array([5., 4., 3., 2., 1.])

### Indixing and Slicing in Multiple Dimensions

In [106]:
b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [107]:
b[0]

array([1., 4., 7.])

In [108]:
b[2, 2]

np.float64(9.0)

In [109]:
b[:,1] # The symbol `:` selects the whole axis

array([4., 5., 6.])

In [110]:
b[0, 1:4]

array([4., 7.])

In [111]:
b[:, 1:3]  

array([[4., 7.],
       [5., 8.],
       [6., 9.]])

In [112]:
b[:, 0:5:2]

array([[1., 7.],
       [2., 8.],
       [3., 9.]])

In [113]:
b[::-1]  # reverses axis 0

array([[3., 6., 9.],
       [2., 5., 8.],
       [1., 4., 7.]])

In [114]:
b[::-1, ::-1]  # reverses both axes

array([[9., 6., 3.],
       [8., 5., 2.],
       [7., 4., 1.]])

## Advanced Indexing

In [115]:
d = np.array([10, 15, 2., 5, 10, 2, 1])
d

array([10., 15.,  2.,  5., 10.,  2.,  1.])

In [116]:
mask = np.array([True, False, False, True, False, True, True])
mask

array([ True, False, False,  True, False,  True,  True])

In [117]:
d[mask]

array([10.,  5.,  2.,  1.])

In [118]:
d[[0,3,5,6]]

array([10.,  5.,  2.,  1.])

In [119]:
d[[1, 3, 1, 6]]

array([15.,  5., 15.,  1.])

## Helper Functions to Create Arrays

In [120]:
np.arange(7) # Creates array from a range of integers

array([0, 1, 2, 3, 4, 5, 6])

In [121]:
np.arange(2,7)

array([2, 3, 4, 5, 6])

In [122]:
np.arange(2,7,2)

array([2, 4, 6])

In [123]:
np.linspace(1, 5, 10) #[start, end, number of points in the interval]

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [124]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [125]:
np.ones(10, dtype='i') # Creates an array with ones of the integer type

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [126]:
np.ones(10, dtype='i2')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [127]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [128]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [129]:
np.zeros(5, dtype='i')

array([0, 0, 0, 0, 0], dtype=int32)

In [130]:
np.zeros([2, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [131]:
np.empty(20) # Empty array 

array([5.48098354e-310, 0.00000000e+000, 6.39208973e-310, 6.39208975e-310,
       6.39208975e-310, 6.39208832e-310, 6.39208801e-310, 6.39208831e-310,
       6.39208801e-310, 6.39208801e-310, 6.39208974e-310, 6.39208800e-310,
       6.39208801e-310, 6.39208800e-310, 6.39208966e-310, 6.39208976e-310,
       6.39208938e-310, 6.39208804e-310, 6.39208972e-310, 6.39208976e-310])

In [132]:
np.eye(4) # n-dimensional identity array 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [133]:
b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [134]:
np.ones_like(b) # Array with the shape of array b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Random numbers

In [135]:
np.random.random((3,4))

array([[0.7908633 , 0.39077857, 0.69376751, 0.20733369],
       [0.75708508, 0.85814011, 0.61766479, 0.72579998],
       [0.10404815, 0.39204061, 0.39367482, 0.14302336]])

In [136]:
rng = np.random.default_rng(413)  # Starts the random number generator with seed=413

In [137]:
rng.random((3, 4)) # random number array between 0 and 1  with (shape)

array([[0.04622048, 0.48625808, 0.03210341, 0.07850197],
       [0.99893742, 0.79251717, 0.14096539, 0.20539366],
       [0.39306974, 0.14090258, 0.99557315, 0.68259742]])

In [138]:
rng.integers(1, 10, (3, 10)) # (min, max, shape)

array([[4, 4, 5, 9, 6, 3, 6, 7, 4, 2],
       [7, 5, 9, 1, 4, 1, 3, 4, 2, 4],
       [9, 6, 2, 2, 6, 8, 1, 4, 3, 9]])

In [139]:
rng.uniform(0, 5, (2,5)) # Samples are uniformly distributed over the interval (min, max, shape)

array([[4.6239944 , 3.26359437, 2.9543661 , 2.97639479, 3.62314861],
       [4.6588422 , 3.35944474, 0.31380207, 0.32887797, 2.54815115]])

## Changing the shape of an array

In [140]:
c = np.arange(16)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [141]:
c.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [142]:
g = np.array([0,1,2,3])
g

array([0, 1, 2, 3])

In [143]:
g.shape

(4,)

In [144]:
newg = g[:, np.newaxis]  # inserts a new axis, making it two dimensional
newg

array([[0],
       [1],
       [2],
       [3]])

In [145]:
newg.shape

(4, 1)

Flatten an array

In [146]:
b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [147]:
b.ravel()

array([1., 4., 7., 2., 5., 8., 3., 6., 9.])

In [ ]:
b

## Universal Functions (`ufunc`)

A `ufunc` is a **vectorized wrapper** for a function that takes as inputs the components of an array and returns an equalnumber of outputs.
- Math operations (`add()`, `subtract()`, `square()`, `log10()`, ...)
- Trigonometric functions (`sin()`, `cos()`, `tan()`, `deg2rad()`, ...)
- Comparison functions (`greater()`, `less_equal()`, `fmax()`, ...)

The universal functions all are subclasses of `np.ufunc`

In [ ]:
type(np.cos)  # they all are subclasses of np.ufunc

In [ ]:
b

In [ ]:
np.sqrt(b)

In [ ]:
np.cos(b)

## Creating your own `ufunc` 
It is possible to create a new `ufunc` using `np.frompyfunc(func, nin, nout)`

In [148]:
x = rng.integers(0, 100, 10)
x

array([50, 97, 81, 29, 31, 94, 73, 46, 56, 15])

In [149]:
def f(x):
    return 1 if x > 23 else 0

In [150]:
f(x) # This will raise an error of interpretation

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [151]:
uf = np.frompyfunc(f, 1, 1)

In [152]:
uf(x)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0], dtype=object)

In [153]:
uf(50)

1

## Copies of an array

In [154]:
original = np.arange(10)
original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
ref_to_original = original # The new object will point to `original`
ref_to_original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
ref_to_original[2]= 100
ref_to_original

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

In [157]:
original

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

In [158]:
ref_to_original[2] = 99

original   # changing `ref_to_original` has changed `original` !!!!

array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9])

In [159]:
original = np.arange(10)

copy_of_original = np.copy(original) # Create a copy of the array
copy_of_original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
copy_of_original[2] = 99

copy_of_original, original   # changing `copy_of_original` doesn't change `original` !!!!

(array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [161]:
original = np.arange(10)

single_value = original[5]  # single element access returns a copy
single_value

np.int64(5)

In [162]:
single_value = 9999
original             # not affected when `single_value` is changed

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Slices

In [163]:
original = np.arange(10)

a_slice = original[2:4]    # slice of original
a_slice

array([2, 3])

In [164]:
a_slice[1] = 1000  # changing elements of `a_slice` changes to `original`
a_slice, original

(array([   2, 1000]),
 array([   0,    1,    2, 1000,    4,    5,    6,    7,    8,    9]))

In [165]:
original[3:6] = [101, 102, 103]   # changing 'original' also changes 'slice'
a_slice

array([  2, 101])

## Speed Comparisons

In [2]:
import numpy as np

def my_mean(numbers):
    s = 0
    N = len(numbers)
    for i in range(N):
        s += numbers[i]
    return s/N

numbers = np.arange(1000000)
%timeit my_mean(numbers)

68.7 ms ± 864 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
def my_mean(numbers):
    return sum(numbers)/len(numbers)

numbers = list(range(1000000))
%timeit my_mean(numbers) # Defined function

4.89 ms ± 350 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
numbers = np.arange(1000000)
%timeit np.mean(numbers) # Numpy function

746 μs ± 4.76 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
conda install -n astrocom numba

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 26.1.0

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [6]:
import numba as nb

@nb.jit
def my_mean(numbers):
    s = 0
    N = len(numbers)
    for i in range(N):
        s += numbers[i]
    return s/N

numbers = np.arange(1000000)
%timeit my_mean(numbers)

339 μs ± 49.2 μs per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Speed Comparisons

In [7]:
def my_sum(N):
    s = 0
    for i in range(N):
        s +=i
    return s

%timeit my_sum(100000000)

2.94 s ± 57.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
numbers_to_sum = np.arange(100000000)
%timeit np.sum(numbers_to_sum)

44 ms ± 218 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
@nb.jit
def my_sum(N):
    s = 0
    for i in range(N):
        s +=i
    return s

%timeit my_sum(100000000)

114 ns ± 0.833 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


Use of built-in function is encouraged !!!